3030 migrar tela de parlamentar para vuejs
interlegis/sapl-frontend pull request #9
Opened 2019-12-06 16:55 UTC by ulyssesBML

## Descrição

A logica da tela foi migrada para vuejs

## _Issue_ Relacionada

#3030 
## Motivação e Contexto

## Como Isso Foi Testado?

Manualmente
## Capturas de Tela (se apropriado):

## Tipos de Mudanças

- [ ] _Bug fix_ (alteração que corrige uma _issue_ e não altera funcionalidades já existentes)
- [ ] Nova _feature_ (alteração que adiciona uma funcionalidade e não altera funcionalidades já existentes)
- [ ] Alteração disruptiva (_Breaking change_) (Correção ou funcionalidade que causa alteração nas funcionalidades existentes)

## Checklist:

- [ ] Eu li o documento de Contribuição (**CONTRIBUTING**).
- [ ] Meu código segue o estilo de código desse projeto.
- [ ] Minha alteração requer uma alteração na documentação.
- [ ] Eu atualizei a documentação de acordo.
- [ ] Eu adicionei testes para cobrir minhas mudanças.
- [ ] Todos os testes novos e existentes passaram.

2019-12-09 13:13 UTC, cesaraugc requested changes

2019-12-09 13:13 UTC, cesaraugc commented on src/__apps/parlamentar/main.js
> +var legislaturas = []
```suggestion
```

2019-12-09 13:13 UTC, cesaraugc commented on src/__apps/parlamentar/main.js
> +        console.log("asd")
```suggestion
```

2019-12-09 13:13 UTC, cesaraugc commented on src/__apps/parlamentar/main.js
> +            console.log(response)
```suggestion
```

2019-12-09 13:13 UTC, cesaraugc commented on src/__apps/parlamentar/main.js
> +            console.error("Ocorreu um erro ao pegar os dados de parlamentares")
```suggestion
            console.error("Ocorreu um erro ao obter os dados dos parlamentares.")
```

2019-12-09 13:13 UTC, cesaraugc commented on src/__apps/parlamentar/main.js
> +            console.log(response.data)
```suggestion
```

2019-12-09 13:13 UTC, cesaraugc commented on src/__apps/parlamentar/main.js
> +              console.error("Erro ao procurar parlamentar:" + response);
```suggestion
              console.error("Erro ao procurar parlamentar: " + response);
```

2019-12-09 13:13 UTC, cesaraugc commented on src/__apps/parlamentar/main.js
> +          console.log(response.data.results)
```suggestion
```

2019-12-09 13:13 UTC, cesaraugc commented on src/__apps/parlamentar/main.js
> +          console.log(this.parlamentares)
```suggestion
```

2019-12-09 14:27 UTC, cesaraugc approved these changes

2019-12-09 21:25 UTC, LeandroJatai approved these changes

2019-12-11 17:23 UTC, edwardoliveira approved these changes
LGTM.

2019-12-11 17:24 UTC, merged